[package]
name = "wick-guard"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.89.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { version = "0.11.2", features = ["alloc", "cpi", "account-resize"] }
pinocchio-log = "0.5.1"
pinocchio-system = { version = "0.6", features = ["account-resize"] }

[features]
no-entrypoint = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(solana)'] }

[profile.release]
overflow-checks = true
lto = "thin"
incremental = false
codegen-units = 1